# Generated by Django 2.1.3 on 2018-11-23 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1024)),
                ('type', models.CharField(choices=[('IPV4', 'IPv4 Address'), ('IPV6', 'IPv6 Address'), ('MAC', 'MAC Address')], default='IPV4', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('port', models.SmallIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webway.Protocol')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('nickname', models.CharField(max_length=512)),
                ('interfaces', models.ManyToManyField(to='webway.Interface')),
                ('services', models.ManyToManyField(to='webway.Service')),
            ],
        ),
        migrations.AddField(
            model_name='interface',
            name='addresses',
            field=models.ManyToManyField(to='webway.NetworkAddress'),
        ),
    ]
