# Generated by Django 2.1.3 on 2018-11-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='bind_addr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webway.NetworkAddress'),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='port',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='protocol',
            field=models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ETH', 'Ethernet')], default='TCP', max_length=255),
        ),
        migrations.DeleteModel(
            name='Protocol',
        ),
    ]
